source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '~> 4.0'
gem 'pg'
gem 'active_model_serializers'
gem 'jbuilder'
#gem 'haml-rails'
gem 'rakeflow'

gem 'jquery-rails',     '2.2.2'
gem 'sass-rails'
gem 'coffee-rails'
gem 'zurb-foundation',  '>= 4.0'
gem 'uglifier',         '~> 1.3'

gem 'ember-rails'
gem 'emblem-rails'
gem 'ember_script-rails'

group :development do
  gem 'meta_request'
end

group :development, :test do
  gem 'pry-rails'
  gem 'teaspoon'
end

group :test do
  gem 'rspec-rails'
  #gem 'capybara'
end

group :production do
  #gem 'airbrake'
  gem 'heroku'
end
