taps:
  - tubbo/tap
packages:
  - homer
  - antigen
  - git
  - node
  - bats
  - coreutils
  - mutt
  - ssh-copy-id
  - ruby-install
  - chruby
  - phantomjs
  - postgresql
  - redis
  - mailutils
  - keychain
  - flac
