taps:
  - tubbo/tap
packages:
  - homer
  - antigen
  - git
  - node
  - bats
  - coreutils
  - mutt
  - ssh-copy-id
  - ruby-install
  - chruby
  - phantomjs
  - postgresql
  - redis
  - mailutils
  - keychain
  - flac
  - rails-template
  - terminal-notifier
casks:
  - google-chrome
  - slack
  - sequel-pro
  - psequel
  - virtualbox
  - mailbox
  - bittorrent-sync
  - dropbox
  - vimr
  - the-unarchiver
  - vlc
  - spotify
  - soundcleod
  - utorrent
  - iterm
