.TH dots 1 "Last Modified: June 2013" "DOTS ZSH Framework" "License: MIT"

.SH DOTS - A ZSH framework for power users

.P DOTS is a ZSH framework, originally beginning life as a fork of Oh My
   ZSH. Designed for power users, DOTS takes care of a number of things
   for you, including prompt customization and plugin loading. A user is
   expected to hack the framework and maintain a separate fork of it for
   their own purposes. DOTS was designed to be simple, and efficient.

.SH Commands

.P
  dots reload - Symlink all dotfiles from ~/.dots/config to your home
                directory.
  dots persist FILE - Persist a dotfile from your home dir into ~/.dots/config
  dots forget FILE - Remove a persisted dotfile from the Git repo
  dots update - Update DOTS from upstream and Antigen
