# TelVue Broadcast app

project_name: broadcast
project_root: ~/Code/broadcast
tabs:
  - chat: irssi
  - editor: vim
  - stage:
      layout: even-vertical
      panes:
        - git status
        - ssh picard.teve.inc
