# ~/.tmuxinator/broadcast.yml
# you can make as many tabs as you wish...

project_name: broadcast
project_root: ~/Code/broadcast/dev
#socket_name: foo # Not needed.  Remove to use default socket
#pre: sudo /etc/rc.d/mysqld start
tabs:
  - chat: irssi
  - editor:
      layout: main-vertical
      panes:
        - vim
        - #empty, will just run plain bash
        - top
  - shell: git pull
  - server: rails s
  - logs: rl development
  - database: rails db
  - console: rails c
  - stage: ssh picard
