# A global collection of gems that are used in all dirs.
#
# Add gems here to be included on the whole system.

source :rubygems

group :version_control do
  gem 'git_tracker'
  gem 'git-process'
end

group :development_tools do
  gem 'rails'
  gem 'pv'
end

group :configuration_management do
  gem 'zsh_dots' # keep up to date with the latest version
end
