# Master configuration for all shells.
#
# Environment variable definitions go here, but that's about it. All
# other definitions go into zshrc or lib/plugins.

# Set the path to our shell configuration.
ZSH=$HOME/.dots
DOTS=$ZSH

# Domain-specific PATHs.
RBPATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims:/usr/local/lib/ruby/gems/1.9.1/bin:vendor/gems/bin
JSPATH=node_modules/.bin:/usr/local/share/npm/bin
PYPATH=/usr/local/Cellar/python/2.7.3/bin:/usr/local/share/python
GOPATH=$HOME/Code/Go
PGPATH=/Applications/Postgres.app/Contents/MacOS/bin
MANPATH=/opt/local/share/man:$MANPATH
HEROKU_PATH="/usr/local/heroku/bin"
CPATH=/usr/local/bin:/usr/local/sbin:/usr/local/git/bin:/usr/bin:$HOME/bin:bin

# Global PATH, the variable that really matters
PATH=$PGPATH:$RBPATH:$JSPATH:$PYPATH:$CPATH:$PATH

alias reset_path='export PATH=$RBPATH:$PGPATH:$CPATH:$PYPATH:$MLPATH:$JSPATH:$PATH'

# Use WebKit Nightly
BROWSER=/Applications/Webkit.app/Contents/MacOS/webkit

# Force 256 color terminals
TERM=screen-256color

# Text editing and paging
EDITOR='vim'
PAGER='less -R'

# Email reading
MAIL=/var/mail/$USER

# A more basic version of my promptstring for non-interactive shells.
PROMPT="♬  "

# PostgreSQL config
ARCHFLAGS='-arch x86_64'
PGDATA=/usr/local/var/postgres

# Configure the MySQL prompt to show more information.
MYSQL_PS1="\R:\m:\s \h> "

# Disable weekly automatic update.
DISABLE_AUTO_UPDATE="true"

# Don't set iTerm/Terminal's title automatically.
DISABLE_AUTO_TITLE="true"

# Display red dots when ZSH is hanging.
COMPLETION_WAITING_DOTS="true"

# Make Ruby even faster
RUBY_HEAP_MIN_SLOTS=1000000
RUBY_HEAP_SLOTS_INCREMENT=1000000
RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
RUBY_GC_MALLOC_LIMIT=1000000000
RUBY_HEAP_FREE_MIN=500000

# Always use Bundler with RVM.
USE_BUNDLER=force

# Set this to a different Git remote to pull updates from there.
# NOTE: You will have to manage updating from upstream yourself.
DOTS_REMOTE='origin'

# Colorize Grep
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'

# Use the Turn testing engine on eLocal
export USE_TURN=true

# Load Java on OS X
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home/

# Load the framework.
source $ZSH/lib/dots.sh

# Load Boxen
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# Override git log
alias gl='nocorrect git blog'

# Load rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Hack to get around PostgreSQL not always being socket-connectable
export PGHOST='localhost'

# Use vagrant-digitalocean
export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt

# Execute autoenv
source ~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-kennethreitz-SLASH-autoenv.git/activate.sh
