# ZSH configuration for interactive shells.
#
# Basically sets up your PROMPT/RPROMPT strings with colors, so
# everything looks pretty.

local path_prompt="%{$reset_color%}%~"
PROMPT="%m %{$fg[white]%}♬  %{$reset_color%}"
RPROMPT="%{$fg[yellow]%}${path_prompt}"

# Use 'viins' mappings for *most* inline command editing
bindkey -v

# Re-bind history search actions so that the text already typed into
# the prompt is used to filter results. When typing "rake" into the
# prompt and hitting the up arrow, only results that match /^rake/
# will be returned.
bindkey '^R' history-incremental-search-backward
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward

# added by travis gem
#source /Users/tscott/.travis/travis.sh
